---
title: "Merging datasets in R"
output:
  html_document:
    css: ~/GitHub/IALSA.github.io/www/css/basic.css
    fig.retina: 2
    fig_width: 8
    toc: yes
    theme: united
    keep_md: true
  md_document:
    toc: yes
    toc_depth: 3
  pdf_document:
    fig_caption: no
    fig_crop: no
    fig_width: 8
    latex_engine: xelatex
    number_sections: yes
    toc: yes
    toc_depth: 3
  word_document:
    fig_width: 6.5
mainfont: Calibri
---

<!--  Set the working directory to the repository's base directory; this assumes the report is nested inside of only one directory.-->
```{r, echo=F, message=F} 
require(knitr)
opts_knit$set(root.dir='../')  #Don't combine this call with any other chunk -especially one that uses file paths.

```

```{r set_options, echo=F, message=F}
require(knitr)
# getwd()
opts_chunk$set(
  results='show', 
  message = TRUE,
  comment = NA, 
  tidy = FALSE,
#   fig.height = 4.8, 
#   fig.width = 6.5, 
#   out.width = "550px",
  fig.path = 'figure_rmd/',     
  dev = "png",
#   fig.path = 'figure_pdf/',     
#   dev = "pdf",
  dpi = 400
)
echoChunks <- FALSE
warningChunks<- FALSE
options(width=120) #So the output is 50% wider than the default.
read_chunk("./merging/merging.R") # the file to which knitr calls for the chunks
```

Suppose we would like to merge several datafiles.

```{r LoadData, echo=TRUE, message=TRUE}
ds<- ds
```

Now we can inspect the created file
```{r}
head(ds,7)
str(ds)
summary(ds)
```


